Update crontab for jobs
AugurProject/turbo pull request #1262
Opened 2021-09-18 01:00 UTC by pgebheim

2021-09-18 01:23 UTC, justinbarry commented
LGTM

2021-10-04 16:26 UTC, robert-e-davidson3 requested changes

2021-10-04 16:26 UTC, robert-e-davidson3 commented on packages/chainlink/docker/jobs_creator/templates/mma-create.json
> +        "schedule": "CRON_TZ=UTC 10 * * 1"
This is missing a field, no?

2021-10-04 20:07 UTC, robert-e-davidson3 approved these changes

2021-10-05 17:09 UTC, justinbarry approved these changes
LGTM

2021-10-05 17:09 UTC, merged