Add events to master chef
AugurProject/turbo pull request #1277
Opened 2021-09-21 07:30 UTC by justinbarry

2021-09-21 23:33 UTC, robert-e-davidson3 approved these changes
I'm gonna take your word on the tests being correct. The code change looks very straight-forward.

2021-09-21 23:36 UTC, robert-e-davidson3 requested changes
Somehow I missed most of the changes. Blocking since I don't know how to undo an approval.

2021-09-21 23:42 UTC, robert-e-davidson3 submitted a review, later dismissed

2021-09-21 23:42 UTC, robert-e-davidson3 commented on packages/smart/contracts/rewards/MasterChef.sol
> +        uint256 _pid = _rewardPoolLookupInfo.pid;
This doesn't seem to be read anywhere.

2021-09-21 23:42 UTC, robert-e-davidson3 commented on packages/smart/contracts/rewards/MasterChef.sol
> +            require(_bPool != BPool(0), "Pool not created.");
Will people be able to make pools with the AMMFactory directly? It looks like if they do then the pool will forever be ineligible for rewards.

2021-09-22 18:55 UTC, justinbarry commented on packages/smart/contracts/rewards/MasterChef.sol
> +        uint256 _pid = _rewardPoolLookupInfo.pid;
Good catch!

2021-09-23 00:00 UTC, bthaile approved these changes
Lgtm

2021-09-23 16:37 UTC, merged