filter identical h2h markets
AugurProject/turbo pull request #745
Opened 2021-06-09 13:03 UTC by andrewdamelio

https://github.com/AugurProject/turbo/issues/636

2021-06-10 20:05 UTC, bthaile commented
filter out in contract-calls.ts so the same market isn't loaded each block.

2021-06-10 20:06 UTC, bthaile requested changes
should do this logic in market loading and filter out of data.markets

2021-06-14 14:40 UTC, andrewdamelio commented
> should do this logic in market loading and filter out of data.markets

👍 makes sense

2021-06-17 12:29 UTC, andrewdamelio commented
@bthaile updated

2021-06-17 21:30 UTC, bthaile commented on packages/comps/src/utils/contract-calls.ts
> +  Object.keys(marketInfos).forEach((market) => {
There is already a constant for spread.

2021-06-17 21:33 UTC, bthaile commented on packages/comps/src/utils/contract-calls.ts
> +    if (marketInfos[market].sportsMarketType === SPORTS_MARKET_TYPE_SPREAD && marketInfos[market].spreadLine === 5) {
Keep all the filtering and removing logic in on place “ getMarketInfos” is the place

2021-06-17 21:33 UTC, bthaile requested changes
Added comments

2021-06-18 17:10 UTC, bthaile commented on packages/comps/src/utils/contract-calls.ts
> +            marketInfos[id].spreadLine === 5 &&
"5" should prob be "0" when the line is zero

2021-06-18 17:10 UTC, bthaile requested changes
made a comment

2021-06-18 19:32 UTC, bthaile approved these changes
lgtm

2021-06-18 19:32 UTC, merged