add setIsRpcDown/isRpcDown
AugurProject/turbo pull request #853
Opened 2021-06-25 19:26 UTC by andrewdamelio

https://github.com/AugurProject/turbo/issues/780
<img width="444" src="https://user-images.githubusercontent.com/1683736/123475430-64219f80-d5c9-11eb-974f-339c0b89458f.png">
<img width="444" src="https://user-images.githubusercontent.com/1683736/123475434-64ba3600-d5c9-11eb-9e7a-3dd9c4df626b.png">

2021-06-25 21:41 UTC, bthaile commented on packages/simplified/src/modules/market/trading-form.tsx
> +        if (error?.message) {
This only catches if user is making a trade. There are other situations where rpc being down effects the user. 

Example when user isn't logged in and rpc endpoint is down, markets don't get loaded or don't get updated. 
Also if user is trying to add liquidity. 

Need to catch these situations, look at adding this catch in data store. 
`packages/comps/src/stores/data.tsx` when `getMarketInfos` is called, that will catch the majority of issues with rpc.

2021-06-25 21:41 UTC, bthaile requested changes
see comment

2021-07-05 18:04 UTC, andrewdamelio commented
@bthaile will fix!

2021-07-07 19:55 UTC, bthaile approved these changes
approved

2021-07-07 19:55 UTC, merged